class_name Enum extends Node

enum message {
	TEST, # test messages
	ID, # ws peer id
	LOGIN,
	LOGIN_SUCCESS,
	LOGIN_ERROR,
	SIGNUP,
	SIGNUP_SUCCESS,
	SIGNUP_ERROR,
	MATCH_CREATE,
	MATCH_CREATE_SUCCESS,
	MATCH_CREATE_ERROR,
	MATCH_LIST,
	LOBBY,
	MATCH_JOIN,
	MATCH_CONNECTED,
	MATCH_LEAVE,
	MATCH_DISCONNECTED,
	MATCH_START,
	WEBRTC_OFFER,
	WEBRTC_ANSWER,
	WEBRTC_EXCHANGE
}
